<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>HesabrasYar.Wallet</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\HesabrasYar.Wallet.Application\HesabrasYar.Wallet.Application.csproj" />
    <ProjectReference Include="..\HesabrasYar.Wallet.Domain.Tests\HesabrasYar.Wallet.Domain.Tests.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1.0" />
  </ItemGroup>

</Project>
